final List<String> campuses = [
  
  'Aryabhatt DSEU Ashok Vihar Campus',
  'Ambedkar DSEU Shakarpur Campus - I',
  'Bhai Parmanand DSEU Shakarpur Campus - II',
  'G.B. Pant DSEU Okhla-I Campus',
  'DSEU Okhla-II Campus',
  'GB Pant DSEU Okhla-III Campus',
  'Guru Nanak Dev DSEU Rohini Campus',
  'DSEU Pusa Campus',
  'DSEU Dwarka Campus',
  'DSEU Siri Fort Campus',
  'Kasturba DSEU Pitampura Campus',
  'Meerabai DSEU Maharani Bagh Campus',
  'DSEU Rajokri Campus',
  'DSEU Vivek Vihar Campus',
  'DSEU Wazirpur-I Campuss',
  'Centre for Healthcare, Allied Medical and Paramedical Sciences',
  'DSEU Dheerpur Campus',
  'DSEU Mayur Vihar Campus',
];
